name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Pozwala ręcznie uruchomić workflow

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Debug Information
      run: |
        echo "Current directory:"
        pwd
        echo "Repository contents:"
        ls -la

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install Dependencies
      run: |
        npm ci
        echo "Installed packages:"
        npm list --depth=0

    - name: Build Project
      run: |
        npm run build
        echo "Build directory contents:"
        ls -la build

    - name: List Build Contents
      run: |
        echo "Detailed build contents:"
        find build -type f

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        full_commit_message: ${{ github.event.head_commit.message }}

    - name: Debug Deployment
      if: failure()
      run: |
        echo "Deployment failed. Check the previous steps for more information."
